# Generated by Django 5.1.6 on 2025-05-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_todos_alter_patients_conditions_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('MedicoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('PacienteID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('FechaNacimiento', models.DateField(blank=True, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(max_length=128)),
                ('TipoUsuario', models.CharField(choices=[('Paciente', 'Paciente'), ('Medico', 'Medico')], default='Paciente', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='consult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='todo',
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('HorarioID', models.AutoField(primary_key=True, serialize=False)),
                ('DiaSemana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('HoraInicio', models.TimeField()),
                ('HoraFin', models.TimeField()),
                ('MedicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medico')),
            ],
            options={
                'unique_together': {('MedicoID', 'DiaSemana', 'HoraInicio')},
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('HistoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaConsulta', models.DateTimeField(auto_now_add=True)),
                ('Diagnostico', models.TextField(blank=True, null=True)),
                ('Tratamiento', models.TextField(blank=True, null=True)),
                ('NotasAdicionales', models.TextField(blank=True, null=True)),
                ('MedicoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.medico')),
                ('PacienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('CitaID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaCita', models.DateField()),
                ('HoraCita', models.TimeField()),
                ('MedioCita', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=10)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=10)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('MedicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medico')),
                ('PacienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.paciente')),
            ],
            options={
                'unique_together': {('MedicoID', 'FechaCita', 'HoraCita')},
            },
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Consult',
        ),
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
