# Generated by Django 5.1.6 on 2025-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medico_paciente_remove_consult_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Precio en USD', max_digits=6),
        ),
    ]
